### ISSUE TITLE
event_rule_role_arn input ignored in event targets

### ISSUE THREAD

**Issue by tim-faase** [cn-terraform/terraform-aws-ecs-fargate-scheduled-task#5]
Providing event_rule_role_arn input to module is ignored and `module.ecs-fargate-scheduled-task.aws_iam_role.scheduled_task_cw_event_role` is used in event target.

```
  # module.ecs-fargate-scheduled-task.aws_cloudwatch_event_target.ecs_scheduled_task will be created
  + resource "aws_cloudwatch_event_target" "ecs_scheduled_task" {
      + arn            = "arn:aws:ecs:ap-southeast-2:445645794583:cluster/hydrofluxdr-prod"
      + event_bus_name = "default"
      + id             = (known after apply)
      + role_arn       = (known after apply)
```

https://github.com/cn-terraform/terraform-aws-ecs-fargate-scheduled-task/blob/main/main.tf#L64

**Comment by jnonino** [comment]
Hi, how are you?

`event_rule_role_arn` is not ignored, it is used in this resource:

```
resource "aws_cloudwatch_event_rule" "event_rule" {
  name                = var.event_rule_name
  schedule_expression = var.event_rule_schedule_expression
  event_bus_name      = var.event_rule_event_bus_name
  event_pattern       = var.event_rule_event_pattern
  description         = var.event_rule_description
  role_arn            = var.event_rule_role_arn
  is_enabled          = var.event_rule_is_enabled
  tags = {
    Name = "${var.name_prefix}-cw-event-rule"
  }
}
```

Are you sure you need to have `event_rule_role_arn` in the event target (`module.ecs-fargate-scheduled-task.aws_cloudwatch_event_target.ecs_scheduled_task`)??

**Comment by tim-faase** [comment]
The event target specifies a [RoleArn](https://github.com/cn-terraform/terraform-aws-ecs-fargate-scheduled-task/blob/main/main.tf#L23), CloudTrail reported a failure of the event wanting to assume to role of Task and Task Execution.
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/events/put-targets.html#options

`{"errorMessage": "User: arn:aws:sts::##:assumed-role/corporate-dev-cli-st-cw-role/## is not authorized to perform: iam:PassRole on resource: arn:aws:iam::##:role/##-task-role-dev-app"}`

**Comment by jnonino** [comment]
Hi @tim-faase, did the change in [PR-7](https://github.com/cn-terraform/terraform-aws-ecs-fargate-scheduled-task/pull/7) solve the issue?

**Comment by tim-faase** [comment]
@jnonino yes, sorry for not advising

**Comment by jnonino** [comment]
No problem @tim-faase, thanks. Please let me know if you have any other issue!!
