### ISSUE TITLE
Built-in IAM Role fails when Task Definition includes a task role

### ISSUE THREAD

**Issue by kevouellet** [cn-terraform/terraform-aws-ecs-fargate-scheduled-task#6]
As per AWS documentation on the matter:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/CWE_IAM_role.html

> If your scheduled tasks require the use of the task execution role, **a task role**, or a task role override, then you must add iam:PassRole permissions for each task execution role, task role, or task role override to the CloudWatch Events IAM role.

Using the built-in Scheduled Task CW Event Role doesn't work if the task definition includes a task role. This is because the Terraform code doesn't add them to the IAM role as roles to be passed using the action "iam:PassRole".

### Workaround
Changing the role_arn value to the default ecsEvents role via WebUI or API works, because of the role being more permissive.

**Comment by jnonino** [comment]
Release in version 1.0.17.
Thanks for your contribution!!!
